language: generic
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
sudo: true
before_install: 
- sudo apt-get install cmake
- sudo apt-get install libpq-dev
- sudo apt-get install gcc-6 g++-6
compiler: gcc
install: cd build && cmake .. && make
