language: generic
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpq-dev gcc-6 cmake
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
sudo: required
install: cd build && cmake .. && make
notifications:
  email: false
